### PR TITLE
Added datepicker and date validation

### PR DESCRIPTION
**Pull request by iambibhas**
Relates to #51

### CODE REVIEW

**Comment by anandology** [comment]
Awesome! Thanks @iambibhas.

**Comment by iambibhas** [comment]
@anandology hey, test it once yourself. :)

**Comment by anandology** [comment]
Sorry, @iambibhas I had to revert your changes.

With `<input type="date">` the mobile devices will have native date control and browser also show a date picker (even though not as good as the one you added). Your commit shows the same datepicker on all platforms. The font is too small to touch on mobiles. I would like to go with the default `type="date"`.

**Comment by iambibhas** [comment]
Hmm. But I'm not sure how many people would use this from mobile device. And on desktop, it doesn't have any datepicker etc. If not this, we should add a `placeholder` text on the date field that shows the acceptable date format. That's the only reason I added a datepicker.

**Pull request merged**
