### PR TITLE
Added link to github profile

### PR DESCRIPTION
**Pull request by tarzzz**
This commit adds a link to the github profile of a user. A screenshot of implementation from my local version
selection_019

### CODE REVIEW

**Comment by shrayasr** [comment]
I think this addresses #6 ?

**Comment by tarzzz** [comment]
Yes @shrayasr Precisely.

**Comment by anandology** [comment]
Could you please add github logo and just the github userid, linked to the github profile?

**Comment by anandology** [comment]
@tarzzz squashed merged you commits. Also added the github logo. Thanks! (closes #6)

**Pull request closed without merging**
